name: Build

on:
  workflow_call:
    inputs:
      os:
        description: Runner label (e.g. ubuntu-latest, windows-latest, macos-latest)
        required: false
        type: string
        default: ubuntu-latest
      node_version_file:
        description: Path to .nvmrc (or .node-version)
        required: false
        type: string
        default: .nvmrc
      working_directory:
        description: Directory to run steps in
        required: false
        type: string
        default: .
      checkout:
        description: Whether to checkout the repo
        required: false
        type: boolean
        default: true
    secrets:
      NPM_TOKEN:
        required: false

defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.working_directory }}

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout
        if: ${{ inputs.checkout }}
        uses: actions/checkout@v4

      - name: Setup Node from file
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
          cache: pnpm

      - name: Configure NPM auth (optional)
        if: ${{ secrets.NPM_TOKEN != '' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}"
          npm whoami || true

      - name: Enable Corepack
        run: corepack enable