name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      # Node from .nvmrc; no pnpm cache here (pnpm not on PATH yet)
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      # Make pnpm available according to package.json > packageManager (Corepack ships with Node)
      - name: Enable Corepack
        run: corepack enable

      # Linux-only: start a Postgres service via Docker to exercise DB integration
      - name: Start Postgres (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          docker rm -f cursor_usage_tracker_pg || true
          docker run --name cursor_usage_tracker_pg \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_DB=cursor_usage_tracker \
            -p 5432:5432 \
            -d postgres:15

      - name: Wait for Postgres (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          for i in {1..60}; do
            if docker exec cursor_usage_tracker_pg pg_isready -U postgres; then
              echo "Postgres ready"; break;
            fi
            sleep 1
          done

            # Cache pnpm store (works the same on Linux & Windows)

      - name: Compute pnpm store path
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm --version
      - run: pnpm install --frozen-lockfile

      - name: Prisma Generate
        run: pnpm --filter @cursor-usage/db run db:generate

      - name: Build
        run: pnpm build

      - name: Print and Validate Config (Success Case)
        run: pnpm print:config
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
          REDIS_URL: "redis://localhost:6379"
          AUTH_SECRET: "test-secret"

      - name: Validate Config (Failure Case) [Unix]
        run: |
          # This command is expected to fail, so we invert the exit code.
          # `&& exit 1` makes the step fail if the command succeeds.
          # `|| exit 0` makes the step succeed if the command fails.
          SMTP_PORT="not-a-number" pnpm print:config && exit 1 || exit 0

      - run: pnpm lint

      # - name: Typecheck
      #   run: pnpm typecheck

      - name: Test
        run: pnpm test
