name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      # Use Node version from your .nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      # Make pnpm available via Corepack and honor package.json > packageManager
      - name: Enable Corepack (pnpm)
        run: corepack enable

      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test